### ISSUE TITLE
React 组件实例

### ISSUE THREAD

**Issue by ubbcou** [ubbcou/blog#11]
![image](https://github.com/ubbcou/blog/blob/master/Examples/images/menu-btn-on.png?raw=true)
![image](https://github.com/ubbcou/blog/blob/master/Examples/images/menu-btn-off.png?raw=true)
> css
```css
html, body, #root {
  width: 100%;
  height: 100%;
  margin: 0;
}
.MenuButton {
  position: relative;
  width: 25px;
  height: 25px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-around;
  overflow: hidden;
}

.MenuButton .line {
  display: block;
  width: 20px;
  height: 5px;
  border-radius: 3px;
  background-color: #333;
  transition: all .3s;
}

.MenuButton.on .line{
  position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    margin: auto;
}
.MenuButton.on .top {
  transform: rotateZ(45deg);
}
.MenuButton.on .line.bottom{
  transform: rotateZ(-45deg);
}
.MenuButton.on .line.center{
  transform: translate(-120%);
}


```
> js
```javascript
class MenuButton extends React.Component {
  constructor(props) {
    super(props);
    this.handleClick = this.handleClick.bind(this);
    this.state = {
      isOpenMenu: false
    };
  };
  
  handleClick() {
    this.setState({
      isOpenMenu: !this.state.isOpenMenu
    })
  }
  
  render() {
    return (
      <div className={this.state.isOpenMenu?'MenuButton on':'MenuButton'} onClick={this.handleClick}>
        <span className="line top"></span>
        <span className="line center"></span>
        <span className="line bottom"></span>
      </div>
    )
  }
}

function App() {
  return (
    <div>
      <MenuButton />
    </div>
  )
}

ReactDOM.render(
  <App />,
  document.getElementById('root')
)
```
